import { book } from "@/types/book";

export const mockBooks: book[] = [
  {
    id: 1,
    ten_sach: "Nhà Giả Kim",
    isbn: "9786041234567",
    tac_gia: "Paulo Coelho",
    mo_ta_ngan: "Tiểu thuyết được đọc nhiều nhất thế giới, kể về hành trình theo đuổi giấc mơ của chàng chăn cừu Santiago.",
    gia_goc: 110000,
    gia_ban: 85000,
    so_luong_ton: 20,
    so_luong_da_ban: 320,
    nam_xuat_ban: 2022,
    ngon_ngu: "Tiếng Việt",
    anh_bia: "/images/book/imgbook1.jpg",
    trang_thai: "Còn hàng",
    id_the_loai: 1,
    id_nha_xuat_ban: 1,
  },
  {
    id: 2,
    ten_sach: "Đắc Nhân Tâm",
    isbn: "9786041234568",
    tac_gia: "Dale Carnegie",
    mo_ta_ngan: "Cuốn sách kinh điển về nghệ thuật giao tiếp và ứng xử, giúp bạn thành công trong cuộc sống.",
    gia_goc: 120000,
    gia_ban: 90000,
    so_luong_ton: 15,
    so_luong_da_ban: 500,
    nam_xuat_ban: 2021,
    ngon_ngu: "Tiếng Việt",
    anh_bia: "/images/book/imgbook2.jpg",
    trang_thai: "Còn hàng",
    id_the_loai: 2,
    id_nha_xuat_ban: 1,
  },
  {
    id: 3,
    ten_sach: "Tuổi Trẻ Đáng Giá Bao Nhiêu",
    isbn: "9786041234569",
    tac_gia: "Rosie Nguyễn",
    mo_ta_ngan: "Cuốn sách truyền cảm hứng cho giới trẻ về cách sống có ý nghĩa và theo đuổi đam mê.",
    gia_goc: 100000,
    gia_ban: 78000,
    so_luong_ton: 12,
    so_luong_da_ban: 280,
    nam_xuat_ban: 2020,
    ngon_ngu: "Tiếng Việt",
    anh_bia: "/images/book/imgbook3.jpg",
    trang_thai: "Còn hàng",
    id_the_loai: 2,
    id_nha_xuat_ban: 1,
  },
  {
    id: 4,
    ten_sach: "Cây Cam Ngọt Của Tôi",
    isbn: "9786041234570",
    tac_gia: "José Mauro de Vasconcelos",
    mo_ta_ngan: "Câu chuyện cảm động về cậu bé Zezé và cây cam ngọt, một kiệt tác văn học Brazil.",
    gia_goc: 125000,
    gia_ban: 95000,
    so_luong_ton: 8,
    so_luong_da_ban: 260,
    nam_xuat_ban: 2023,
    ngon_ngu: "Tiếng Việt",
    anh_bia: "/images/book/imgbook4.jpg",
    trang_thai: "Còn hàng",
    id_the_loai: 1,
    id_nha_xuat_ban: 1,
  },
  {
    id: 5,
    ten_sach: "Atomic Habits - Thay Đổi Tí Hon, Hiệu Quả Bất Ngờ",
    isbn: "9786041234571",
    tac_gia: "James Clear",
    mo_ta_ngan: "Phương pháp khoa học để xây dựng thói quen tốt và loại bỏ thói quen xấu.",
    gia_goc: 150000,
    gia_ban: 115000,
    so_luong_ton: 25,
    so_luong_da_ban: 450,
    nam_xuat_ban: 2023,
    ngon_ngu: "Tiếng Việt",
    anh_bia: "/images/book/imgbook5.jpg",
    trang_thai: "Còn hàng",
    id_the_loai: 2,
    id_nha_xuat_ban: 2,
  },
  {
    id: 6,
    ten_sach: "Sapiens - Lược Sử Loài Người",
    isbn: "9786041234572",
    tac_gia: "Yuval Noah Harari",
    mo_ta_ngan: "Cuốn sách best-seller toàn cầu về lịch sử phát triển của loài người từ thời tiền sử đến hiện đại.",
    gia_goc: 199000,
    gia_ban: 155000,
    so_luong_ton: 10,
    so_luong_da_ban: 180,
    nam_xuat_ban: 2022,
    ngon_ngu: "Tiếng Việt",
    anh_bia: "/images/book/imgbook6.jpg",
    trang_thai: "Còn hàng",
    id_the_loai: 3,
    id_nha_xuat_ban: 2,
  },
  {
    id: 7,
    ten_sach: "Tôi Tài Giỏi, Bạn Cũng Thế!",
    isbn: "9786041234573",
    tac_gia: "Adam Khoo",
    mo_ta_ngan: "Bí quyết học tập hiệu quả và phát huy tiềm năng bản thân từ chuyên gia giáo dục Singapore.",
    gia_goc: 135000,
    gia_ban: 99000,
    so_luong_ton: 18,
    so_luong_da_ban: 350,
    nam_xuat_ban: 2021,
    ngon_ngu: "Tiếng Việt",
    anh_bia: "/images/book/imgbook7.jpg",
    trang_thai: "Còn hàng",
    id_the_loai: 2,
    id_nha_xuat_ban: 1,
  },
  {
    id: 8,
    ten_sach: "Dế Mèn Phiêu Lưu Ký",
    isbn: "9786041234574",
    tac_gia: "Tô Hoài",
    mo_ta_ngan: "Tác phẩm kinh điển của văn học thiếu nhi Việt Nam, kể về cuộc phiêu lưu của chú Dế Mèn.",
    gia_goc: 65000,
    gia_ban: 65000,
    so_luong_ton: 30,
    so_luong_da_ban: 200,
    nam_xuat_ban: 2020,
    ngon_ngu: "Tiếng Việt",
    anh_bia: "/images/book/imgbook1.jpg",
    trang_thai: "Còn hàng",
    id_the_loai: 4,
    id_nha_xuat_ban: 1,
  },
  {
    id: 9,
    ten_sach: "Nghĩ Giàu Làm Giàu",
    isbn: "9786041234575",
    tac_gia: "Napoleon Hill",
    mo_ta_ngan: "Cuốn sách kinh điển về tư duy làm giàu, đã truyền cảm hứng cho hàng triệu người trên thế giới.",
    gia_goc: 110000,
    gia_ban: 82000,
    so_luong_ton: 0,
    so_luong_da_ban: 150,
    nam_xuat_ban: 2019,
    ngon_ngu: "Tiếng Việt",
    anh_bia: "/images/book/imgbook2.jpg",
    trang_thai: "Hết hàng",
    id_the_loai: 2,
    id_nha_xuat_ban: 2,
  },
  {
    id: 10,
    ten_sach: "Hai Số Phận",
    isbn: "9786041234576",
    tac_gia: "Jeffrey Archer",
    mo_ta_ngan: "Tiểu thuyết hấp dẫn kể về cuộc đời song song của hai người đàn ông sinh cùng ngày nhưng khác số phận.",
    gia_goc: 180000,
    gia_ban: 135000,
    so_luong_ton: 5,
    so_luong_da_ban: 90,
    nam_xuat_ban: 2023,
    ngon_ngu: "Tiếng Việt",
    anh_bia: "/images/book/imgbook3.jpg",
    trang_thai: "Còn hàng",
    id_the_loai: 1,
    id_nha_xuat_ban: 1,
  },
  {
    id: 11,
    ten_sach: "English Grammar In Use",
    isbn: "9786041234577",
    tac_gia: "Raymond Murphy",
    mo_ta_ngan: "Sách ngữ pháp tiếng Anh bán chạy nhất thế giới, phù hợp cho người tự học.",
    gia_goc: 250000,
    gia_ban: 195000,
    so_luong_ton: 22,
    so_luong_da_ban: 420,
    nam_xuat_ban: 2024,
    ngon_ngu: "Tiếng Anh",
    anh_bia: "/images/book/imgbook5.jpg",
    trang_thai: "Còn hàng",
    id_the_loai: 6,
    id_nha_xuat_ban: 2,
  },
  {
    id: 12,
    ten_sach: "Doraemon - Tập 1",
    isbn: "9786041234578",
    tac_gia: "Fujiko F. Fujio",
    mo_ta_ngan: "Bộ truyện tranh nổi tiếng nhất Nhật Bản về chú mèo máy đến từ tương lai.",
    gia_goc: 25000,
    gia_ban: 25000,
    so_luong_ton: 50,
    so_luong_da_ban: 600,
    nam_xuat_ban: 2022,
    ngon_ngu: "Tiếng Việt",
    anh_bia: "/images/book/imgbook6.jpg",
    trang_thai: "Còn hàng",
    id_the_loai: 4,
    id_nha_xuat_ban: 3,
  },
];